#%RAML 1.0 Library
usage: Defines standard structure of a Policy 

types: 
  policy:
    properties: 
      policyId: string
      policyTypeCode: string
      policyTypeDescription?: string
      policyHolderId: string
      policyHolderName: string
      certificateNumber: string
      dealerCode?: string
      itemDescription?: string
      manufacturer: string
      model?: string
      ProductCode?: string
      ProductDescription?: string
      SKUNumber?: string
      SerialNumber?: string
      ServiceLineNumber?: string
      Statuscode: string
      WarrantySalesDate: string
      WorkPhone?: string



