#%RAML 1.0
title: Policy Data API

traits: 
  pageable: !include exchange_modules/38c843c0-bd64-4ba4-be17-76104765ad01/pageable-trait/1.0.0/pageable-trait.raml
  client-id-secured: !include exchange_modules/38c843c0-bd64-4ba4-be17-76104765ad01/client-id-secured-trait/1.0.0/client-id-secured-trait.raml
uses: 
  Policy: /exchange_modules/38c843c0-bd64-4ba4-be17-76104765ad01/policy-data-type/1.0.0/policy-data-type.raml
types: 
  objectName: Policy.policy

/policy:
  displayName: Policy
  description: |
    Working with Polcies:
    * Retrieving all available policies
    * Creating Policies
  get:
    description: |
      Retrieve all the Policies.
    is: [ pageable, client-id-secured ]
    queryParameters:
      type:
        displayName: The policy type
        minLength: 0
        maxLength: 255
    responses:
      200:
        body:
          application/json:
            type: objectName
  post:
    description: |
      Create a new Policy
    body:
      application/json:
        type: objectName[]
    #    example: !include ./examples/policy_post_request_example.json
    responses:
      201:
        description: Created
        body:
          application/json:
            type: objectName
  /{id}:
    displayName: Policy ID
    uriParameters:
      id:
        type: string
        example: '6798836789'
        description: Represents the unique policy id
    get:
      description: Get Policy by ID
      responses:
        200:
          body:
            application/json:
              type: objectName
              
        400:
          body:
            application/json:
              example: |
                {
                  "message": "Bad message"
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Resource not found"
                }
    put:
      body:
        application/json:
          type: objectName
      responses:
        204:
    delete:
      responses:
        204: